version: '3'
services:
        web:
                image: nginx:1.13.5-alpine
                ports:
                        - "80:80"
                volumes:
                        - ./data/www:/var/www
                        - ./web/default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - app
                restart: "always"
                tty: true

        app:
                build: ./app
                env_file: ./.env
                environment:
                        DATABASE_HOST: db
                depends_on:
                        - db
                volumes:
                        - ./data/www:/var/www
                restart: "always"
                tty: true

        db:
                image: mysql:8
                env_file: ./.env
                ports:
                        - "3306:3306"
                volumes:
                        - ./data/db:/var/lib/mysql
                tty: true
                command: --innodb-use-native-aio=0

        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                environment:
                        - PMA_ARBITRARY=1
                        - PMA_HOST=db
                        - PMA_USER=root
                        - PMA_PASSWORD=root
                        - PMA_PORT=3306
                ports:
                        - "8080:80"
                depends_on:
                        - db
                # volumes:
                #         - /vagrant/docker/phpmyadmin/sessions:/sessions
